const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const API='https://graphql.anilist.co';
let ANIME_DATA=[];
const seasonJP={WINTER:'冬',SPRING:'春',SUMMER:'夏',FALL:'秋'};
const seasonName=(year,season)=>`${year}年${seasonJP[season]||season}`;
const currentSeason=()=>{const m=new Date().getMonth()+1;return m<=3?'WINTER':m<=6?'SPRING':m<=9?'SUMMER':'FALL'};
const currentYear=()=>new Date().getFullYear();
const gql=async(query,variables={})=>{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({query,variables})});if(!r.ok)throw new Error('API HTTP '+r.status);const j=await r.json();if(j.errors)throw new Error(j.errors[0]?.message||'API error');return j.data};
const listQuery=`query($page:Int,$perPage:Int,$season:MediaSeason,$seasonYear:Int,$search:String){Page(page:$page,perPage:$perPage){pageInfo{hasNextPage total}media(type:ANIME,season:$season,seasonYear:$seasonYear,search:$search,sort:[POPULARITY_DESC]){id title{romaji native english}coverImage{large extraLarge}description(asHtml:false)startDate{year month day}season seasonYear format episodes status genres averageScore studios(isMain:true){nodes{name}}source siteUrl popularity countryOfOrigin characters(sort:ROLE,perPage:8){edges{role node{name{full}} voiceActors(language:JAPANESE){name{full}}}}staff(perPage:20){edges{role node{name{full}}}}streamingEpisodes{title site url}}}}}`;
const normalize=a=>({id:String(a.id),title:a.title?.native||a.title?.romaji||a.title?.english||'名称不明',kana:a.title?.english||a.title?.romaji||'',season:seasonName(a.seasonYear||currentYear(),a.season),date:[a.startDate?.year,a.startDate?.month,a.startDate?.day].filter(Boolean).map((v,i)=>i?String(v).padStart(2,'0'):v).join('-')||'未定',weekday:'',time:'',genre:a.genres||[],studio:a.studios?.nodes?.[0]?.name||'未定',source:a.source||'不明',description:(a.description||'').replace(/\s+/g,' ').trim(),image:a.coverImage?.extraLarge||a.coverImage?.large||'',official:a.siteUrl||'',streaming:(a.streamingEpisodes||[]).map(x=>x.site).filter(Boolean),cast:(a.characters?.edges||[]).map(x=>[x.node?.name?.full||'',x.voiceActors?.[0]?.name?.full||'']).filter(x=>x[0]),staff:(a.staff?.edges||[]).map(x=>[x.role||'',x.node?.name?.full||'']).filter(x=>x[0]),score:a.averageScore||0,popularity:a.popularity||0});
const card=a=>`<article class="card"><a href="anime.html?id=${encodeURIComponent(a.id)}"><div class="cover">${a.image?`<img loading="lazy" src="${esc(a.image)}" alt="${esc(a.title)}">`:'ANIME DATA'}${a.score?`<b class="score">★ ${(a.score/10).toFixed(2)}</b>`:''}</div><div class="body"><span class="tag">${esc(a.season)}</span><h3>${esc(a.title)}</h3><p>${esc(a.genre.slice(0,3).join(' / '))}</p><small>${esc(a.date)}　${esc(a.studio)}</small></div></a></article>`;
function fillSeasons(){const s=document.querySelector('#season');const names=[...new Set(ANIME_DATA.map(a=>a.season))];names.sort().reverse();s.innerHTML='<option value="">すべてのクール</option>'+names.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');document.querySelector('#seasonButtons').innerHTML=names.map(x=>`<button data-s="${esc(x)}">${esc(x)}</button>`).join('');}
function renderHome(){const q=document.querySelector('#q'),s=document.querySelector('#season'),g=document.querySelector('#grid');const render=()=>{const t=q.value.trim().toLowerCase(),v=s.value;const list=ANIME_DATA.filter(a=>(!v||a.season===v)&&(!t||[a.title,a.kana,a.studio,a.source,...a.genre].join(' ').toLowerCase().includes(t)));g.innerHTML=list.map(card).join('');document.querySelector('#count').textContent=list.length+'作品';document.querySelector('#heading').textContent=t||v?'検索結果':seasonName(currentYear(),currentSeason())+'アニメ';document.querySelector('#empty').hidden=!!list.length;};q.oninput=render;s.onchange=render;document.querySelector('#clear').onclick=()=>{q.value='';s.value='';render()};document.querySelector('#seasonButtons').onclick=e=>{if(e.target.dataset.s){s.value=e.target.dataset.s;render();scrollTo({top:300,behavior:'smooth'})}};render();document.querySelector('#popularGrid').innerHTML=[...ANIME_DATA].sort((a,b)=>(b.popularity||0)-(a.popularity||0)).slice(0,6).map(card).join('');}
function detail(){const id=new URLSearchParams(location.search).get('id'),a=ANIME_DATA.find(x=>x.id===id),d=document.querySelector('#detail');if(!a){d.innerHTML='<div class="empty"><h1>作品が見つかりません</h1><a href="./">一覧へ戻る</a></div>';return}document.title=a.title+'｜ANIME DATA';d.innerHTML=`<div class="detailtop"><div class="detailcover">${a.image?`<img src="${esc(a.image)}" alt="${esc(a.title)}">`:'ANIME DATA'}</div><div><span class="tag">${esc(a.season)}</span><h1>${esc(a.title)}</h1><p class="kana">${esc(a.kana)}</p><p class="desc">${esc(a.description||'作品情報を準備中です。')}</p><div class="facts"><div><b>放送開始</b>${esc(a.date)}</div><div><b>ジャンル</b>${esc(a.genre.join(' / '))}</div><div><b>制作会社</b>${esc(a.studio)}</div><div><b>原作</b>${esc(a.source)}</div><div><b>評価</b>${a.score?esc((a.score/10).toFixed(2)):'-'}</div></div>${a.official?`<a class="btn" href="${esc(a.official)}" target="_blank" rel="noopener">作品ページ</a>`:''}</div></div><div class="cols"><section><h2>キャスト</h2>${a.cast.length?a.cast.map(x=>`<p class="row"><b>${esc(x[0])}</b><span>${esc(x[1]||'')}</span></p>`).join(''):'<p>情報なし</p>'}</section><section><h2>スタッフ</h2>${a.staff.length?a.staff.slice(0,15).map(x=>`<p class="row"><b>${esc(x[0])}</b><span>${esc(x[1])}</span></p>`).join(''):'<p>情報なし</p>'}</section></div><section><h2>配信情報</h2><div class="chips">${a.streaming.length?a.streaming.map(x=>`<span>${esc(x)}</span>`).join(''):'<span>配信情報なし</span>'}</div></section>`;}
async function start(){try{if(location.pathname.endsWith('anime.html')){const id=new URLSearchParams(location.search).get('id');const data=await gql(listQuery,{page:1,perPage:50,season:currentSeason(),seasonYear:currentYear()});ANIME_DATA=data.Page.media.map(normalize);if(id&&!ANIME_DATA.some(a=>a.id===id)){const r=await gql(listQuery,{page:1,perPage:1,search:id});ANIME_DATA.push(...r.Page.media.map(normalize).filter(a=>a.id===id));}detail();return}const data=await gql(listQuery,{page:1,perPage:50,season:currentSeason(),seasonYear:currentYear()});ANIME_DATA=data.Page.media.map(normalize);document.querySelector('#liveStatus').textContent=`${currentYear()}年${seasonJP[currentSeason()]}アニメ ${ANIME_DATA.length}作品`;document.querySelector('#notice').hidden=true;}catch(e){console.error(e);ANIME_DATA=[...FALLBACK_ANIME];const n=document.querySelector('#notice');if(n){n.hidden=false;n.textContent='最新データを取得できなかったため、フォールバックデータを表示しています。時間を置いて再読み込みしてください。'}if(document.querySelector('#liveStatus'))document.querySelector('#liveStatus').textContent='オフライン表示'}if(location.pathname.endsWith('anime.html'))detail();else{fillSeasons();renderHome();}}
start();
